name: Compile Sass

on:
  push:
    branches:
      - main


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: Checkout new gh-pages branch
        uses: actions/checkout@v2
        with:
            ref: gh-pages
            fetch-depth: 10
      
      - name: Move gh-pages to main branch
        run: |
          git rebase --onto main gh-pages gh-pages
      
      - name: Delete development gitignore
        run: |
          rm .gitignore

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.5
        with:
          source: styles/index.scss
          destination: styles/index.css

      - name: Add and commit changes to gh-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Actionz'
          git add styles/*
          git commit -m 'Compile website'

      - name: Push changes to gh-pages
        uses: dfm/force-push-branch-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          commit-message: "Compile website"
          path: *