name: Compile Sass

on:
  push:
    branches:
      - main


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true
      
      - name: Delete development gitignore
        run: |
          rm .gitignore

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.5
        with:
          source: styles/index.scss
          destination: styles/index.css
      
      - name: Tidy up surplus Sass files
        run: |
          find . -name "*.scss" | xargs rm

      - name: Push changes to gh-pages
        uses: dfm/force-push-branch-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target-branch: "gh-pages"
          commit-message: "Compile stylesheets"
          path: "*"
