name: Compile Sass

on:
  push:
    branches:
      - main


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: main
            fetch-depth: 10
            submodules: true
      
      - name: Create fresh gh-pages branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'gh-pages'

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
            ref: gh-pages
            fetch-depth: 1
      
      - name: Delete .gitignore
        run: |
          rm .gitignore

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.5
        with:
          source: styles/index.scss
          destination: styles/index.css

      - name: Add and Commit changes to gh-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add styles/*
          git commit -m 'Compile website'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages