name: Compile Sass

on:
  push:
    branches:
      - main


jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true
      
      - name: Delete development gitignore
        run: |
          rm .gitignore

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.5
        with:
          source: styles/index.scss
          destination: styles/index.css
      
      - name: Tidy up surplus Sass files
        run: |
          find . -name "*.scss" | xargs rm

      - name: Push changes to gh-pages
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Actionz'
          git fetch --all
          git checkout -B gh-pages
          git add -f *
          git rm .gitignore
          git commit -m "Compile stylesheets"
          git push -f --set-upstream origin gh-pages
